apiVersion: v1
data:
  Corefile: |
    supercluster.local:53 {
        forward . dnsip
    }
    .:53 {
        errors
        health
        log
        kubernetes cluster1.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
